# create new person
post http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "testing name",
  "number": "0000000000"
}

###
# This is a success request
get http://localhost:3001/api/persons/"replace with above id"

###
# This is a error request
get http://localhost:3001/api/persons/100

###
# delete person
delete http://localhost:3001/api/persons/"replace with above id"