# create person
post http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "testing name",
  "number": "00000000"
}

###
# Update person
put http://localhost:3001/api/persons/"replace with above id"
Content-Type: application/json

{
  "name": "testing name",
  "number": "111111111"
}

###
# Delete person
delete http://localhost:3001/api/persons/"replace with above id"